      - name: Save disk info to file
        run: df -h / > disk_space.txt

      - name: Upload log
        uses: actions/upload-artifact@v4
        with:
          name: disk-space-log
          path: disk_space.txt
          retention-days: 1
